# Generated by Django 6.0.6 on 2026-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom', models.CharField(max_length=100)),
                ('pinyin', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField()),
                ('example_scenario', models.TextField(blank=True)),
                ('audio_scenario_file', models.FileField(blank=True, null=True, upload_to='idiom_scenarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pinyin', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='pronunciations/')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sentences/')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pinyin', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='vocabulary_audio/')),
            ],
        ),
    ]
