# Generated by Django 4.2.30 on 2026-06-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_idiomcategory_sentencecategory_vocabularycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
