# Generated by Django 4.2.30 on 2026-06-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_idiomcategory_created_at_sentencecategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiomcategory',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='sentencecategory',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='vocabularycategory',
            old_name='title',
            new_name='category_name',
        ),
    ]
