# Generated by Django 4.2.30 on 2026-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_rename_title_idiomcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='english_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='english_translation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
