# Generated by Django 4.2.30 on 2026-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_idiom_english_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='pinyin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
