# Generated by Django 4.2.30 on 2026-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_sentence_pinyin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronunciation',
            name='word',
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='chinese_example',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='english_example',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='pinyin_example',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='symbol',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pronunciation',
            name='pinyin',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
