# Generated by Django 4.2.30 on 2026-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_pronunciation_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('example', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='tones/')),
            ],
        ),
    ]
