# Generated by Django 4.2.30 on 2026-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tone',
            name='tone_name',
            field=models.CharField(choices=[('First Tone', 'First Tone'), ('Second Tone', 'Second Tone'), ('Third Tone', 'Third Tone'), ('Fourth Tone', 'Fourth Tone')], max_length=50),
        ),
    ]
