# Generated by Django 4.2.30 on 2026-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_tone_tone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tone',
            name='symbol',
            field=models.CharField(choices=[('ˉ', 'First Tone'), ('ˊ', 'Second Tone'), ('ˇ', 'Third Tone'), ('ˋ', 'Fourth Tone')], max_length=5),
        ),
    ]
