# Generated by Django 4.2.30 on 2026-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_tone_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tone',
            name='description',
            field=models.CharField(choices=[('High Level', 'High Level'), ('Rising', 'Rising'), ('Falling-Rising', 'Falling-Rising'), ('Falling', 'Falling')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tone',
            name='symbol',
            field=models.CharField(choices=[('ˉ', '-'), ('ˊ', 'ˊ'), ('ˇ', 'ˇ'), ('ˋ', 'ˋ')], max_length=5),
        ),
    ]
