# Generated by Django 4.2.30 on 2026-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_tone_description_alter_tone_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tone',
            name='base_pinyin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
