# Generated by Django 4.2.30 on 2026-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_tone_base_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='expression_type',
            field=models.CharField(choices=[('idiom', 'Idiom'), ('proverb', 'Proverb'), ('saying', 'Saying'), ('phrase', 'Phrase'), ('slang', 'Slang'), ('quotation', 'Quotation')], default='idiom', max_length=30, verbose_name='Expression Type'),
        ),
    ]
