# Generated by Django 4.2.30 on 2026-08-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_learningsurvey_surveyresponse_surveyquestion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('response', 'question')},
        ),
    ]
