# Generated by Django 4.2.30 on 2026-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_alter_surveyanswer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsurvey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
