# Generated by Django 4.2.30 on 2026-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_alter_learningsurvey_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='level',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced'), ('all', 'All Levels')], default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='level',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced'), ('all', 'All Levels')], default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='sentence',
            name='level',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced'), ('all', 'All Levels')], default='unclassified', max_length=20),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='level',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced'), ('all', 'All Levels')], default='unclassified', max_length=20),
        ),
    ]
