# Generated by Django 4.2.30 on 2026-08-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_studentgroup'),
        ('teacher', '0018_idiom_level_pronunciation_level_sentence_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsurvey',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='course.studentgroup'),
        ),
    ]
