# Generated by Django 4.2.30 on 2026-08-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_learningsurvey_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiom',
            name='example_scenario',
        ),
        migrations.AddField(
            model_name='idiom',
            name='example_pinyin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='idiom',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='idiom',
            name='example_translation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_pinyin',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_translation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
