# Generated by Django 4.2.30 on 2026-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_remove_idiom_example_scenario_idiom_example_pinyin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsurvey',
            name='availability_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days students can access this survey after it becomes available'),
        ),
        migrations.AddField(
            model_name='learningsurvey',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
