# Generated by Django 4.2.30 on 2026-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_studentgroup'),
        ('teacher', '0022_vocabulary_allowed_groups_vocabulary_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='sentence_materials', to='course.studentgroup'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Students'), ('groups', 'Selected Groups')], default='all', max_length=20),
        ),
    ]
