# Generated by Django 4.2.30 on 2026-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_privacypolicy_termsofservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced')], max_length=20)),
                ('prompt', models.TextField()),
                ('choice_a', models.CharField(max_length=500)),
                ('choice_b', models.CharField(max_length=500)),
                ('choice_c', models.CharField(max_length=500)),
                ('choice_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=1)),
                ('audio', models.FileField(blank=True, null=True, upload_to='placement_audio/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
