# Generated by Django 4.2.30 on 2026-08-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
