# Generated by Django 4.2.30 on 2026-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='learning_level',
            field=models.CharField(choices=[('level1', 'Level I'), ('level2', 'Level II'), ('level3', 'Level III')], default='level1', max_length=10),
        ),
    ]
