# Generated by Django 5.2.17 on 2026-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_learning_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address_hash', models.CharField(db_index=True, max_length=64)),
                ('total_correct', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('overall_percentage', models.PositiveSmallIntegerField()),
                ('recommended_level', models.CharField(choices=[('level1', 'Level I - Beginner'), ('level2', 'Level II - Intermediate'), ('level3', 'Level III - Advanced')], max_length=10)),
                ('result_email', models.EmailField(blank=True, max_length=254)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
