# Generated by Django 4.2.30 on 2026-06-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_student_e9e22a_idx',
            old_name='class_booki_student_f272c8_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_timeslo_b45923_idx',
            old_name='class_booki_timeslo_2524f0_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='course.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='course.course'),
        ),
    ]
