# Generated by Django 4.2.30 on 2026-06-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_student_e9e22a_idx',
            old_name='course_booki_student_f272c8_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_timeslo_b45923_idx',
            old_name='course_booki_timeslo_2524f0_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
