# Generated by Django 4.2.30 on 2026-06-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_class_booki_student_f272c8_idx_course_book_student_e9e22a_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_student_e9e22a_idx',
            old_name='course_booki_student_f272c8_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='course_book_timeslo_b45923_idx',
            old_name='course_booki_timeslo_2524f0_idx',
        ),
    ]
