# Generated by Django 4.2.30 on 2026-07-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_course_booki_student_f272c8_idx_course_book_student_e9e22a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_timezone',
            field=models.CharField(default='America/Chicago', help_text='Time zone used when creating this course schedule.', max_length=64),
        ),
    ]
