# Generated by Django 4.2.30 on 2026-07-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_teacher_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_transfer_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
