# Generated by Django 4.2.30 on 2026-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_course_booki_student_f272c8_idx_course_book_student_e9e22a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
