# Generated by Django 4.2.30 on 2026-06-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_tutoringpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_name',
        ),
    ]
