# Generated by Django 4.2.30 on 2026-06-15 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_remove_subscription_subscriber_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringpayment',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tutoringpayment',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutoringpayment',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
