# Generated by Django 4.2.30 on 2026-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_tutoringpayment_platform_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
