# Generated by Django 4.2.30 on 2026-08-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_paypal_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
