"""Han-era story lessons for the PandaSpeak History Journey."""


def vocab(word, pinyin, meaning):
    return {"word": word, "pinyin": pinyin, "meaning": meaning}


def lesson(slug, level, era, icon, title, chinese_title, intro, passage, vocabulary,
           today, speak_prompts, question, choices, answer):
    return {
        "slug": slug, "level": level, "era": era, "icon": icon,
        "title": title, "chinese_title": chinese_title, "intro": intro,
        "passage": passage, "vocabulary": vocabulary, "today": today,
        "speak_prompts": speak_prompts,
        "quiz": {"question": question, "choices": choices, "answer": answer},
    }


HAN_HISTORY_LESSONS = {
    "hongmen-banquet": lesson("hongmen-banquet", "level2", "Chu–Han Transition", "🍶", "The Feast at Hong Gate", "鴻門宴",
        "Enter the tense banquet where Liu Bang faced Xiang Yu after the fall of Qin.",
        "秦朝滅亡後，劉邦和項羽成為最重要的兩股力量。劉邦先進入關中，引起項羽不滿。項羽在鴻門設宴，范增希望趁機除掉劉邦。宴會中氣氛非常緊張，項莊舞劍，意在攻擊劉邦。最後劉邦在樊噲等人的幫助下離開鴻門。",
        [vocab("鴻門宴", "Hóngmén Yàn", "Feast at Hong Gate"), vocab("劉邦", "Liú Bāng", "Liu Bang"), vocab("項羽", "Xiàng Yǔ", "Xiang Yu"), vocab("宴會", "yànhuì", "banquet"), vocab("樊噲", "Fán Kuài", "Fan Kuai")],
        "「鴻門宴」今天也可以比喻表面友好、實際上暗藏危險的場合。", ["劉邦為什麼去鴻門？", "你覺得項羽為什麼沒有殺劉邦？"],
        "鴻門宴中，劉邦面對的主要對手是誰？", ["項羽", "漢武帝", "曹操", "王莽"], "項羽"),
    "songs-of-chu": lesson("songs-of-chu", "level2", "Chu–Han Contention", "🎵", "Songs of Chu from All Sides", "四面楚歌",
        "Learn how a battlefield situation became one of China's best-known idioms.",
        "楚漢相爭後期，項羽的軍隊在垓下被漢軍包圍。夜裡，楚軍聽到四面傳來楚地的歌聲，以為家鄉已經被漢軍占領，軍心因此更加低落。項羽最後突圍失敗。「四面楚歌」後來用來形容一個人四面受敵、陷入孤立無援的困境。",
        [vocab("四面楚歌", "sì miàn Chǔ gē", "songs of Chu from all sides"), vocab("垓下", "Gāixià", "Gaixia"), vocab("包圍", "bāowéi", "to surround"), vocab("軍心", "jūnxīn", "army morale"), vocab("困境", "kùnjìng", "difficult situation")],
        "「四面楚歌」至今仍是常用成語，可以用在工作、政治或生活中形容孤立的處境。", ["歌聲為什麼影響楚軍？", "你會在什麼情況使用「四面楚歌」？"],
        "「四面楚歌」最常形容什麼？", ["四面受敵的困境", "熱鬧的音樂會", "旅行四方", "慶祝勝利"], "四面受敵的困境"),
    "farewell-my-concubine": lesson("farewell-my-concubine", "level3", "Chu–Han Contention", "🌙", "The Hegemon-King Bids Farewell to His Lady", "霸王別姬",
        "Explore the tragic farewell associated with Xiang Yu and Consort Yu.",
        "垓下被圍時，項羽知道形勢非常危急。傳統故事中，他在營帳裡飲酒作歌，感嘆自己的力量和命運，虞姬陪伴在旁。這段故事後來被文學、戲曲和電影不斷改編，成為「霸王別姬」的著名文化記憶。",
        [vocab("霸王", "bàwáng", "hegemon-king"), vocab("虞姬", "Yú Jī", "Consort Yu"), vocab("垓下", "Gāixià", "Gaixia"), vocab("告別", "gàobié", "to bid farewell"), vocab("戲曲", "xìqǔ", "traditional opera")],
        "歷史人物常透過後世文學與戲劇形成新的文化形象。", ["為什麼悲劇故事容易被後世記住？", "歷史和戲劇可能有哪些不同？"],
        "「霸王別姬」中的霸王通常指誰？", ["項羽", "劉邦", "韓信", "班超"], "項羽"),
    "han-xin-humiliation": lesson("han-xin-humiliation", "level2", "Early Han", "🗡️", "Han Xin Endures Humiliation", "韓信胯下之辱",
        "See how the young Han Xin endured humiliation before becoming a famous commander.",
        "韓信年輕時生活困苦。有一次，一個人故意羞辱他，要求他從自己的胯下爬過去。韓信沒有因一時憤怒而打鬥，而是忍下羞辱。後來韓信成為劉邦的重要將領。這個故事常用來談忍耐、判斷和長遠目標。",
        [vocab("韓信", "Hán Xìn", "Han Xin"), vocab("胯下之辱", "kuàxià zhī rǔ", "humiliation of crawling between the legs"), vocab("忍耐", "rěnnài", "endurance"), vocab("羞辱", "xiūrǔ", "humiliation"), vocab("將領", "jiànglǐng", "general")],
        "面對挑釁時，控制情緒和考慮長期後果仍是值得討論的能力。", ["韓信為什麼選擇忍耐？", "忍耐和軟弱有什麼不同？"],
        "韓信後來成為誰的重要將領？", ["劉邦", "秦始皇", "周武王", "曹操"], "劉邦"),
    "secret-chencang": lesson("secret-chencang", "level3", "Chu–Han Contention", "🛤️", "Repair the Roads Openly, Advance Secretly through Chencang", "明修棧道，暗渡陳倉",
        "Learn a famous strategy associated with Liu Bang's return from Hanzhong.",
        "楚漢相爭初期，劉邦的勢力在漢中。後世常用「明修棧道，暗渡陳倉」概括漢軍迷惑對手、從另一條路線出兵的策略。這個說法和韓信的軍事形象密切相關，也成為形容表面做一件事、暗中採取另一個行動的成語。",
        [vocab("棧道", "zhàndào", "plank road"), vocab("陳倉", "Chéncāng", "Chencang"), vocab("策略", "cèlüè", "strategy"), vocab("迷惑", "míhuò", "to mislead"), vocab("出兵", "chūbīng", "to send troops")],
        "這個典故今天常被用來描述聲東擊西或隱藏真正計畫的策略。", ["為什麼軍事行動需要保密？", "這個成語今天可以怎麼使用？"],
        "「暗渡陳倉」強調哪一種策略？", ["隱藏真正行動", "公開所有計畫", "停止行軍", "修建宮殿"], "隱藏真正行動"),
    "xiao-he-pursues-han-xin": lesson("xiao-he-pursues-han-xin", "level3", "Early Han", "🌙", "Xiao He Pursues Han Xin by Moonlight", "蕭何月下追韓信",
        "Discover how Xiao He recognized Han Xin's talent and persuaded Liu Bang to value him.",
        "韓信投靠劉邦後，一開始沒有受到重用，因此離開軍隊。蕭何知道後，連夜追趕韓信，把他帶回來，並向劉邦大力推薦。後來劉邦重用韓信，韓信也在楚漢戰爭中建立重要功勞。",
        [vocab("蕭何", "Xiāo Hé", "Xiao He"), vocab("韓信", "Hán Xìn", "Han Xin"), vocab("推薦", "tuījiàn", "to recommend"), vocab("人才", "réncái", "talent"), vocab("重用", "zhòngyòng", "to place in an important position")],
        "發現人才只是第一步，領導者是否願意給人才機會同樣重要。", ["蕭何為什麼追韓信？", "領導者應該怎麼辨認人才？"],
        "蕭何追趕韓信的主要原因是什麼？", ["認為他是重要人才", "向他借錢", "邀請他旅行", "和他比武"], "認為他是重要人才"),
    "wen-jing-prosperity": lesson("wen-jing-prosperity", "level3", "Western Han", "🌾", "The Prosperity of Emperors Wen and Jing", "文景之治",
        "See how lighter government and economic recovery strengthened the early Han.",
        "漢文帝和漢景帝統治時期，政府重視恢復經濟、減輕部分賦稅和徭役，也以節儉聞名。經過秦末和楚漢戰爭的破壞，社會逐漸恢復，國家財力增加。後世把這段相對穩定繁榮的時期稱為「文景之治」。",
        [vocab("文景之治", "Wén-Jǐng zhī Zhì", "Prosperity of Wen and Jing"), vocab("賦稅", "fùshuì", "taxes"), vocab("徭役", "yáoyì", "labor service"), vocab("節儉", "jiéjiǎn", "frugality"), vocab("恢復", "huīfù", "to recover")],
        "戰爭後的經濟恢復往往需要時間，也需要政府政策和社會穩定。", ["為什麼減輕負擔有助於恢復經濟？", "節儉對政府有什麼作用？"],
        "「文景之治」主要和哪兩位皇帝有關？", ["漢文帝、漢景帝", "秦始皇、秦二世", "光武帝、漢獻帝", "唐太宗、唐玄宗"], "漢文帝、漢景帝"),
    "tiying-saves-father": lesson("tiying-saves-father", "level3", "Western Han", "📜", "Tiying Saves Her Father", "緹縈救父",
        "Meet the young woman whose petition became associated with reform of harsh punishments.",
        "漢文帝時，淳于意因犯罪被判刑，他的女兒緹縈一路跟到長安，並上書皇帝，希望代父受罰。她的請求讓漢文帝重新思考殘酷的肉刑制度，之後推動相關改革。「緹縈救父」成為孝親與法律改革的著名故事。",
        [vocab("緹縈", "Tíyíng", "Tiying"), vocab("上書", "shàngshū", "to submit a petition"), vocab("刑罰", "xíngfá", "punishment"), vocab("改革", "gǎigé", "reform"), vocab("孝", "xiào", "filial devotion")],
        "個人的申訴有時也能促使社會重新討論法律是否公平。", ["緹縈為什麼上書？", "法律制度為什麼需要改革？"],
        "緹縈的故事和哪一項改變有關？", ["刑罰改革", "造紙", "絲路開通", "長城修建"], "刑罰改革"),
    "zhang-qian-western-regions": lesson("zhang-qian-western-regions", "level3", "Emperor Wu Era", "🐫", "Zhang Qian's Mission to the Western Regions", "張騫出使西域",
        "Follow Zhang Qian's difficult missions that expanded Han knowledge of Central Asia.",
        "漢武帝派張騫出使西域，希望聯絡其他勢力共同對抗匈奴。張騫途中被匈奴扣留多年，後來仍完成艱難旅程並回到漢朝。他帶回許多關於中亞地區的資訊，促進漢朝與西域的外交、交通和交流。",
        [vocab("張騫", "Zhāng Qiān", "Zhang Qian"), vocab("西域", "Xīyù", "Western Regions"), vocab("匈奴", "Xiōngnú", "Xiongnu"), vocab("出使", "chūshǐ", "to go on a diplomatic mission"), vocab("交流", "jiāoliú", "exchange")],
        "張騫的旅程常被放在絲綢之路形成與跨文化交流的歷史背景中討論。", ["張騫出使西域的目的之一是什麼？", "長途旅行如何改變人們對世界的認識？"],
        "張騫主要奉誰之命出使西域？", ["漢武帝", "漢高祖", "秦始皇", "光武帝"], "漢武帝"),
    "wei-qing-huo-qubing": lesson("wei-qing-huo-qubing", "level3", "Emperor Wu Era", "🐎", "Wei Qing and Huo Qubing Fight the Xiongnu", "衛青、霍去病抗匈奴",
        "Learn about two leading Han commanders in the campaigns against the Xiongnu.",
        "漢武帝時期，漢朝與匈奴長期作戰。衛青和霍去病是重要將領，多次率軍深入北方草原。這些戰爭改變了漢朝北方邊境的軍事形勢，也伴隨龐大的財政與人力成本。",
        [vocab("衛青", "Wèi Qīng", "Wei Qing"), vocab("霍去病", "Huò Qùbìng", "Huo Qubing"), vocab("匈奴", "Xiōngnú", "Xiongnu"), vocab("將領", "jiànglǐng", "general"), vocab("邊境", "biānjìng", "frontier")],
        "研究戰爭不只看勝負，也要思考戰爭對國家資源和人民生活的影響。", ["衛青和霍去病面對的主要對手是誰？", "戰爭可能帶來哪些長期影響？"],
        "衛青和霍去病主要與哪一個對手作戰？", ["匈奴", "蒙古帝國", "倭寇", "太平軍"], "匈奴"),
    "fenglangjuxu": lesson("fenglangjuxu", "level3", "Emperor Wu Era", "🏔️", "Victory at Mount Langjuxu", "封狼居胥",
        "Discover the celebrated phrase associated with Huo Qubing's northern campaign.",
        "霍去病年輕時就成為漢朝名將。西元前一一九年的漠北之戰中，他率軍深入北方。傳統記載說，他在狼居胥山舉行祭天儀式，以紀念軍事勝利。「封狼居胥」後來成為形容武將建立卓越戰功的典故。",
        [vocab("封狼居胥", "fēng Lángjūxū", "ceremony at Mount Langjuxu"), vocab("霍去病", "Huò Qùbìng", "Huo Qubing"), vocab("漠北", "Mòběi", "north of the Gobi"), vocab("戰功", "zhàngōng", "military achievement"), vocab("祭天", "jìtiān", "to offer sacrifice to Heaven")],
        "歷史典故常把複雜的事件濃縮成一句話，因此理解背景很重要。", ["為什麼「封狼居胥」成為著名典故？", "一句成語能完整代表歷史嗎？"],
        "「封狼居胥」最常和哪位將領有關？", ["霍去病", "韓信", "班超", "李廣"], "霍去病"),
    "su-wu-shepherd": lesson("su-wu-shepherd", "level3", "Western Han", "🐑", "Su Wu Tends Sheep", "蘇武牧羊",
        "Hear the story of an envoy remembered for remaining loyal during long captivity.",
        "蘇武奉漢朝命令出使匈奴，後來因政治事件被扣留。傳統記載說，他拒絕投降，被送到北方牧羊，很多年後才回到漢朝。「蘇武牧羊」成為堅持使命和忠誠的著名故事。",
        [vocab("蘇武", "Sū Wǔ", "Su Wu"), vocab("使者", "shǐzhě", "envoy"), vocab("扣留", "kòuliú", "to detain"), vocab("牧羊", "mùyáng", "to herd sheep"), vocab("忠誠", "zhōngchéng", "loyalty")],
        "外交人員代表國家執行任務，有時需要面對非常複雜的政治環境。", ["蘇武為什麼被後世記住？", "忠誠和個人生存之間可能有什麼衝突？"],
        "「蘇武牧羊」主要表現哪一種精神？", ["堅持與忠誠", "追求財富", "發明技術", "建造城市"], "堅持與忠誠"),
    "li-guang": lesson("li-guang", "level3", "Western Han", "🏹", "The Flying General Li Guang", "李廣難封",
        "Meet the celebrated frontier general whose career also became a story about fortune and recognition.",
        "李廣是西漢著名將領，長期在北方邊境與匈奴作戰，以勇敢和騎射能力聞名。匈奴稱他為「飛將軍」。但是李廣一生沒有獲得侯爵封賞，後世因此常用「李廣難封」感嘆有才能的人未必得到理想的機會。",
        [vocab("李廣", "Lǐ Guǎng", "Li Guang"), vocab("飛將軍", "Fēi Jiāngjūn", "Flying General"), vocab("封侯", "fēnghóu", "to be enfeoffed as marquis"), vocab("邊境", "biānjìng", "frontier"), vocab("才能", "cáinéng", "ability")],
        "能力、機會和運氣如何共同影響一個人的生涯，是古今都能討論的問題。", ["李廣為什麼被稱為飛將軍？", "成功只取決於能力嗎？"],
        "「李廣難封」中的李廣以什麼身分聞名？", ["將領", "商人", "醫生", "皇帝"], "將領"),
    "sima-qian-shiji": lesson("sima-qian-shiji", "level3", "Western Han", "📚", "Sima Qian Writes the Records of the Grand Historian", "司馬遷與《史記》",
        "Learn how Sima Qian persevered to complete one of China's foundational historical works.",
        "司馬遷繼承父親的工作，整理和撰寫從上古到漢代的歷史。他因李陵事件替李陵辯護，受到嚴厲刑罰，但仍選擇繼續完成著作。後世把這部作品稱為《史記》，它對中國歷史寫作和文學都有深遠影響。",
        [vocab("司馬遷", "Sīmǎ Qiān", "Sima Qian"), vocab("史記", "Shǐjì", "Records of the Grand Historian"), vocab("歷史", "lìshǐ", "history"), vocab("撰寫", "zhuànxiě", "to write"), vocab("堅持", "jiānchí", "to persevere")],
        "閱讀歷史時，我們也可以思考作者如何選擇、組織和解釋資料。", ["司馬遷為什麼堅持完成《史記》？", "歷史作者會如何影響我們理解過去？"],
        "司馬遷最著名的歷史著作是什麼？", ["《史記》", "《論語》", "《紅樓夢》", "《本草綱目》"], "《史記》"),
    "wang-zhaojun": lesson("wang-zhaojun", "level3", "Western Han", "🎶", "Wang Zhaojun Goes Beyond the Frontier", "王昭君出塞",
        "Explore a famous story of marriage diplomacy between Han China and the Xiongnu.",
        "西漢後期，匈奴呼韓邪單于到漢朝，希望與漢朝建立婚姻關係。宮女王昭君被選中前往匈奴。後世文學把她的故事寫得非常動人，「昭君出塞」也成為漢匈關係與文化交流的重要歷史記憶。",
        [vocab("王昭君", "Wáng Zhāojūn", "Wang Zhaojun"), vocab("出塞", "chūsài", "to go beyond the frontier"), vocab("匈奴", "Xiōngnú", "Xiongnu"), vocab("和親", "héqīn", "marriage diplomacy"), vocab("單于", "chányú", "Xiongnu ruler")],
        "政治婚姻在古代外交中曾被不同國家使用，也會深刻影響當事人的人生。", ["昭君出塞和外交有什麼關係？", "個人命運和國家政策可能如何交織？"],
        "王昭君出塞主要與哪個族群有關？", ["匈奴", "吐蕃", "女真", "契丹"], "匈奴"),
    "guangwu-restoration": lesson("guangwu-restoration", "level3", "Eastern Han", "🌅", "Restoration under Emperor Guangwu", "光武中興",
        "See how Liu Xiu restored Han rule after the upheaval of Wang Mang's Xin dynasty.",
        "西漢末年政治動盪，王莽建立新朝。各地起兵後，劉秀逐漸取得優勢，西元二五年即皇帝位，後來重新統一大部分地區，建立東漢。後世把他恢復漢朝統治並重建秩序的過程稱為「光武中興」。",
        [vocab("光武帝", "Guāngwǔdì", "Emperor Guangwu"), vocab("劉秀", "Liú Xiù", "Liu Xiu"), vocab("王莽", "Wáng Mǎng", "Wang Mang"), vocab("東漢", "Dōng Hàn", "Eastern Han"), vocab("中興", "zhōngxīng", "restoration")],
        "王朝的「恢復」不只是換一位皇帝，也需要重新建立政治與社會秩序。", ["劉秀如何恢復漢朝？", "政治秩序中斷後最需要恢復什麼？"],
        "建立東漢的皇帝是誰？", ["光武帝劉秀", "漢高祖劉邦", "漢武帝劉徹", "漢獻帝劉協"], "光武帝劉秀"),
    "throw-brush-join-army": lesson("throw-brush-join-army", "level3", "Eastern Han", "🖌️", "Throw Away the Writing Brush and Join the Army", "投筆從戎",
        "Learn how Ban Chao left clerical work for a military and diplomatic career.",
        "班超年輕時曾替官府抄寫文書，工作辛苦而且收入不高。他感嘆自己不應該一直做抄寫工作，希望像古代英雄一樣建立功業，於是「投筆從戎」。後來班超在西域從事軍事和外交活動多年。",
        [vocab("投筆從戎", "tóu bǐ cóng róng", "throw down the brush and join the army"), vocab("班超", "Bān Chāo", "Ban Chao"), vocab("文書", "wénshū", "documents"), vocab("從戎", "cóngróng", "to join the military"), vocab("功業", "gōngyè", "achievement")],
        "「投筆從戎」今天仍可用來形容放下文職工作、投身軍旅。", ["班超為什麼改變職業？", "你認為轉換職業需要考慮什麼？"],
        "「投筆從戎」中的「筆」代表什麼工作？", ["文職工作", "農業", "航海", "建築"], "文職工作"),
    "tiger-den": lesson("tiger-den", "level2", "Eastern Han", "🐯", "Nothing Ventured, Nothing Gained", "不入虎穴，焉得虎子",
        "Learn the dramatic Ban Chao story behind a famous expression about taking necessary risks.",
        "班超出使西域時，發現當地國王對漢朝使團的態度突然改變。他判斷匈奴使者可能已經到達，於是決定採取大膽行動。傳統故事中，他說：「不入虎穴，焉得虎子。」意思是不進入危險的地方，就很難得到重要成果。",
        [vocab("不入虎穴，焉得虎子", "bù rù hǔxué, yān dé hǔzǐ", "nothing ventured, nothing gained"), vocab("班超", "Bān Chāo", "Ban Chao"), vocab("使團", "shǐtuán", "diplomatic mission"), vocab("冒險", "màoxiǎn", "to take a risk"), vocab("成果", "chéngguǒ", "result")],
        "這句話今天常用來表示有些重要成果需要承擔合理的風險。", ["班超為什麼決定冒險？", "什麼是合理的風險？"],
        "「不入虎穴，焉得虎子」主要表達什麼？", ["有時需要冒險才能成功", "不要離開家", "老虎很危險", "旅行一定會成功"], "有時需要冒險才能成功"),
    "ban-chao-western-regions": lesson("ban-chao-western-regions", "level3", "Eastern Han", "🗺️", "Ban Chao in the Western Regions", "班超出使西域",
        "Follow Ban Chao's long career rebuilding Eastern Han influence in Central Asia.",
        "東漢時，班超多次在西域活動，透過外交、聯盟和軍事行動恢復漢朝在當地的影響。他在西域生活多年，與許多不同國家往來。班超的經歷顯示古代絲路不只是商品交易，也包含外交與政治競爭。",
        [vocab("班超", "Bān Chāo", "Ban Chao"), vocab("西域", "Xīyù", "Western Regions"), vocab("外交", "wàijiāo", "diplomacy"), vocab("聯盟", "liánméng", "alliance"), vocab("影響", "yǐngxiǎng", "influence")],
        "絲路沿線的交流同時包含商業、文化、外交和安全問題。", ["班超如何擴大漢朝影響？", "外交和軍事有什麼不同？"],
        "班超長期活動的地區是哪里？", ["西域", "江南", "海南", "遼東"], "西域"),
    "cai-lun-paper": lesson("cai-lun-paper", "level3", "Eastern Han", "📄", "Cai Lun and Papermaking", "蔡倫改進造紙術",
        "Explore the traditional account of Cai Lun's role in improving papermaking.",
        "紙在蔡倫以前已經存在。東漢時，蔡倫向朝廷報告改進造紙的方法，使用樹皮、麻、破布和舊漁網等材料。後世常把他和造紙技術的改進聯繫在一起。紙張逐漸成為重要書寫材料，對知識保存和傳播產生巨大影響。",
        [vocab("蔡倫", "Cài Lún", "Cai Lun"), vocab("造紙", "zàozhǐ", "papermaking"), vocab("樹皮", "shùpí", "tree bark"), vocab("材料", "cáiliào", "material"), vocab("傳播", "chuánbō", "to spread")],
        "科技通常是在既有技術上不斷改進，而不一定由一個人在某一天突然發明。", ["紙為什麼改變知識傳播？", "改進技術和發明新技術有什麼不同？"],
        "蔡倫最常和哪一項技術改進有關？", ["造紙", "火藥", "指南針", "印刷"], "造紙"),
    "zhang-heng-seismoscope": lesson("zhang-heng-seismoscope", "level3", "Eastern Han", "⚙️", "Zhang Heng and the Seismoscope", "張衡與地動儀",
        "Meet the Eastern Han scholar associated with an ingenious device for detecting distant earthquakes.",
        "張衡是東漢著名學者，在天文、數學和文學方面都有成就。他製作的候風地動儀可以在地震發生後指示震動來自的大致方向。這台裝置不能像現代儀器一樣測量所有地震數據，但它反映了古人觀察自然和設計機械的能力。",
        [vocab("張衡", "Zhāng Héng", "Zhang Heng"), vocab("地動儀", "dìdòngyí", "seismoscope"), vocab("地震", "dìzhèn", "earthquake"), vocab("方向", "fāngxiàng", "direction"), vocab("機械", "jīxiè", "mechanism")],
        "現代地震學使用精密儀器記錄震波；比較古今設備可以看到工程技術的發展。", ["地動儀能提供什麼資訊？", "古代工程師如何研究看不見的自然現象？"],
        "張衡的地動儀主要和哪種自然現象有關？", ["地震", "颱風", "日食", "洪水"], "地震"),
    "yellow-turban-rebellion": lesson("yellow-turban-rebellion", "level3", "Late Eastern Han", "🟡", "The Yellow Turban Rebellion", "黃巾之亂",
        "See how a massive uprising exposed the deep problems of the late Eastern Han.",
        "東漢末年，社會矛盾加劇，許多農民生活困苦。西元一八四年，張角領導的太平道信眾發動大規模起義，參與者常以黃巾作為標誌，因此被稱為黃巾之亂。朝廷雖然鎮壓了主要起義，但地方軍事力量因此更加強大，漢朝中央權力繼續衰弱。",
        [vocab("黃巾之亂", "Huángjīn zhī Luàn", "Yellow Turban Rebellion"), vocab("張角", "Zhāng Jiǎo", "Zhang Jiao"), vocab("起義", "qǐyì", "uprising"), vocab("鎮壓", "zhènyā", "to suppress"), vocab("衰弱", "shuāiruò", "to weaken")],
        "大型社會動亂往往不是單一原因造成，需要同時觀察經濟、政治和社會因素。", ["黃巾之亂為什麼爆發？", "地方軍事力量變強會如何影響中央政府？"],
        "黃巾之亂爆發於哪一年？", ["184年", "25年", "220年", "618年"], "184年"),
    "dong-zhuo-chaos": lesson("dong-zhuo-chaos", "level3", "End of Eastern Han", "🔥", "Dong Zhuo Seizes Power", "董卓之亂",
        "Follow the power struggle that accelerated the collapse of Eastern Han authority.",
        "東漢末年，朝廷內部鬥爭激烈。董卓率軍進入洛陽後控制朝廷，廢少帝、立漢獻帝，並以軍事力量掌握政權。各地勢力起兵反對董卓，中央政府的控制力進一步崩潰。這段動亂成為漢末群雄割據和三國時代的重要前奏。",
        [vocab("董卓", "Dǒng Zhuó", "Dong Zhuo"), vocab("漢獻帝", "Hàn Xiàndì", "Emperor Xian"), vocab("洛陽", "Luòyáng", "Luoyang"), vocab("割據", "gējù", "regional separatism"), vocab("政權", "zhèngquán", "political power")],
        "依照 PandaSpeak 的朝代分類原則，漢朝滅亡前的故事仍放在漢朝，之後再進入三國。", ["董卓掌權為什麼加速漢朝衰弱？", "中央失去控制後地方勢力會怎麼變化？"],
        "董卓控制朝廷時擁立的是哪位皇帝？", ["漢獻帝", "漢武帝", "漢文帝", "光武帝"], "漢獻帝"),
}

HAN_CARDS = list(HAN_HISTORY_LESSONS.values())
