# Generated by Django 4.2.30 on 2026-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_languagetest_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='choice_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='choice_b',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='choice_c',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='choice_d',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
