# Generated by Django 4.2.30 on 2026-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studenttestsubmission_studentlisteninganswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlisteninganswer',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='choice_a',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='choice_b',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='choice_c',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='choice_d',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
