# Generated by Django 4.2.30 on 2026-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentlisteninganswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
