# Generated by Django 4.2.30 on 2026-08-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_languagetest_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(choices=[('listen_mc', 'Listening - Multiple Choice'), ('speak_read', 'Speaking - Read Aloud')], max_length=20),
        ),
    ]
