# Generated by Django 4.2.30 on 2026-08-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_testquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
