# Generated by Django 4.2.30 on 2026-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_testquestion_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
