# Generated by Django 4.2.30 on 2026-08-18 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_studentgroup'),
        ('student', '0009_languagetest_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_tests', to='course.studentgroup'),
        ),
    ]
