# Generated by Django 4.2.30 on 2026-08-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_languagetest_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspeakinganswer',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answers', to='student.studenttestsubmission'),
        ),
    ]
