# Generated by Django 4.2.30 on 2026-08-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentspeakinganswer_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspeakinganswer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='speaking_answers/'),
        ),
    ]
