# Generated by Django 4.2.30 on 2026-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_learneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetest',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='languagetest',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
